# Generated by Django 5.0.6 on 2024-07-02 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=50)),
                ('education_level', models.CharField(choices=[('pre_primary', 'Pre-Primary'), ('lower_primary', 'Lower Primary'), ('upper_primary', 'Upper Primary'), ('junior_secondary', 'Junior Secondary'), ('senior_secondary', 'Senior Secondary')], max_length=50)),
                ('pathway', models.CharField(blank=True, choices=[('arts_sport_science', 'Arts and Sport Science'), ('social_sciences', 'Social Sciences'), ('stem', 'Science Technology Engineering and Mathematics (STEM)')], max_length=50, null=True)),
                ('track', models.CharField(blank=True, choices=[('arts', 'Arts'), ('sports_science', 'Sports Science'), ('humanities', 'Humanities'), ('languages', 'Languages'), ('business_studies', 'Business Studies'), ('pure_sciences', 'Pure Sciences'), ('applied_sciences', 'Applied Sciences'), ('technical_engineering', 'Technical and Engineering'), ('career_technology', 'Career and Technology Studies')], max_length=50, null=True)),
                ('grade', models.CharField(choices=[('pp1', 'PP1'), ('pp2', 'PP2'), ('1', 'Grade 1'), ('2', 'Grade 2'), ('3', 'Grade 3'), ('4', 'Grade 4'), ('5', 'Grade 5'), ('6', 'Grade 6'), ('7', 'Grade 7'), ('8', 'Grade 8'), ('9', 'Grade 9'), ('10', 'Grade 10'), ('11', 'Grade 11'), ('12', 'Grade 12')], max_length=10)),
            ],
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('subject_name', 'education_level', 'pathway', 'track', 'grade'), name='unique_subject'),
        ),
    ]
