# Generated by Django 5.0.6 on 2024-07-02 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_subject_pathway_alter_subject_track'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subject',
            name='unique_subject',
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('subject_name', 'education_level', 'pathway', 'track', 'grade')},
        ),
    ]
