# Generated by Django 5.0.6 on 2024-07-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_category_options_category_level_category_lft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='display_picture',
            field=models.ImageField(blank=True, null=True, upload_to='test_display_pictures/'),
        ),
    ]
