# Generated by Django 5.0.6 on 2024-07-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_test_display_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
