# Generated by Django 5.0.6 on 2024-07-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='reveal_answer_after_completion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='reveal_explanation_after_completion',
            field=models.BooleanField(default=False),
        ),
    ]
